### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by wimachtendink** [RonPieket/BinaryRelations#1]
https://github.com/RonPieket/BinaryRelations/blob/290afdc826ba40430bfc482ca5d0b946bfed0e89/README.md?plain=1#L23

currently:
"There is a data structure I that has served me..."

"I" should be removed or "use" after "I".

"There is a data structure that has served me..."

"There is a data structure I use that has served me..."

**Comment by RonPieket** [comment]
Thank you. Fixed.
